os: linux
dist: xenial
services:
    - docker 

jobs:
    include:
        - env: DOCKERFILE=tests/docker/Dockerfile.centos8
          name: "CentOS8"
        - env: DOCKERFILE=tests/docker/Dockerfile.centos7
          name: "CentOS7"


before_install:
- uname -a
- docker build tests/docker -f ${DOCKERFILE} -t testimage

install:
- docker run --rm -v $PWD:$PWD -w $PWD testimage make clean
- docker run --rm -v $PWD:$PWD -w $PWD testimage make

script:
- docker run --rm -v $PWD:$PWD -w $PWD testimage bats tests/tests.bats
