os: linux
dist: xenial
services:
    - docker 

jobs:
    include:
        - env: DOCKERFILE=tests/docker/Dockerfile.xenial
          name: "Ubuntu Xenial"
        - env: DOCKERFILE=tests/docker/Dockerfile.bionic
          name: "Ubuntu Bionic"
        - env: DOCKERFILE=tests/docker/Dockerfile.centos7
          name: "CentOS 6"
        - env: DOCKERFILE=tests/docker/Dockerfile.centos7
          name: "CentOS 7"
        - env: DOCKERFILE=tests/docker/Dockerfile.centos8
          name: "CentOS 8"
        - env: DOCKERFILE=tests/docker/Dockerfile.fedora32
          name: "Fedora 32"



before_install:
- uname -a
- docker build tests/docker -f ${DOCKERFILE} -t testimage

install:
- docker run --rm -v $PWD:$PWD -w $PWD testimage make clean
- docker run --rm -v $PWD:$PWD -w $PWD testimage make

script:
- docker run --rm -v $PWD:$PWD -w $PWD testimage bats tests/tests.bats
