dist: xenial
language: C
os: linux
compiler: gcc

before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq bats

install:
- make

script:
- LD_LIBRARY_PATH=$PWD bats tests/tests.bats

after_success:
- coveralls

deploy:
