os: linux
dist: xenial
services:
    - docker 

env:
    - DOCKERFILE=tests/docker/Dockerfile.centos8

before_install:
- uname -a
- docker build tests/docker -f ${DOCKERFILE} -t testimage

install:
- docker run --rm -v $PWD:$PWD -w $PWD testimage make clean
- docker run --rm -v $PWD:$PWD -w $PWD testimage make

script:
- docker run --rm -v $PWD:$PWD -w $PWD testimage bats tests/tests.bats
