name: Publish to GHCR

on:
  push:
    branches: [ master ]
    paths:
      - 'containers/**'
  pull_request:
    branches: [ master ]
    paths:
      - 'containers/**'

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push-base-image:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os-name: [ xenial, bionic, focal, centos7, centos8, fedora32, fedora33, fedora34 ]
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker -  Base images
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ github.actor }}/sea-${{ matrix.os-name }}

      - name: Build and push Docker image - Base images
        uses: docker/build-push-action@v2
        with:
          context: .
          file: containers/base/Dockerfile.${{ matrix.os-name }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  build-and-push-application-image:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        application: [ fmriprep ]
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker - Application images
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ github.actor }}/sea-${{ matrix.application }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: containers/applications/Dockerfile.${{ matrix.application }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
