name: Tests

on:
  push:

  workflow_dispatch:
    inputs:
      debug_enabled:
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'     
        required: false
        default: "false"

jobs:
  install-docker:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        os-name: [xenial, bionic, focal, centos7, centos8, fedora32, fedora33, fedora34]
    name: Test in ${{ matrix.os-name }}
    steps:
      - run: docker --version
      - name: Git checkout
        uses: actions/checkout@v2
      - run: cd ${{ github.workspace }}
      - run: docker build tests/docker -f tests/docker/Dockerfile.${{ matrix.os-name }} -t imagetest:${{ matrix.os-name }}
      - run: docker run --rm -v $PWD:$PWD -w $PWD imagetest:${{ matrix.os-name }} make clean
      - run: docker run --rm -v $PWD:$PWD -w $PWD imagetest:${{ matrix.os-name }} make test debug_opts="-g -ggdb --coverage -fprofile-arcs -ftest-coverage"
      - run: docker run --rm -v $PWD:$PWD -w $PWD imagetest:${{ matrix.os-name }} bats tests/tests.bats
      - run: docker run --rm -v $PWD:$PWD -w $PWD -e SEA_HOME=$PWD -e LD_PRELOAD=$PWD/build/sea.so imagetest:${{ matrix.os-name }} tests/test_custom
      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          gcov_executable: docker run --rm -v $PWD:$PWD -w $PWD imagetest:bionic gcov
          gcov_args: "-abcfu"
      - name: setup tmate session
        if: ${{ failure() && github.event_name == 'workflow_dispatch' && github.event.inputs.debug_enabled == 'true' }}
        uses: mxschmitt/action-tmate@v3


